
apiVersion: argoproj.io/v1alpha1   # API group for ArgoCD resources
kind: Application                  # Resource type is "Application"
metadata:
  name: online-shop-app            # Name of this ArgoCD application
  namespace: argocd                # Must be created in the 'argocd' namespace
spec:
  project: frontend-team                 # ArgoCD Project (logical grouping of apps)
  source:
    repoURL: https://github.com/rohitbhardwajj/Argo-cd.git   # Git repo containing manifests
    targetRevision: main           # Git branch or tag (e.g., main, dev, release-1.0)
    path: nginxfeatures/projects/ymlsFiles   # Path inside repo where manifests live
  destination:
    server: https://172.31.76.233:33893   # Target cluster API
    namespace: nginx             # Namespace in which to deploy the app
  syncPolicy:                      # Defines how ArgoCD syncs the app
    automated:                     # Enable auto-sync
      prune: true                  # Delete resources removed from Git
      selfHeal: true               # Fix drift if resources are changed manually
    syncOptions:
      - CreateNamespace=true
